// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weyhbwuhsirsydbbjicw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndleWhid3Voc2lyc3lkYmJqaWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTA2NjAsImV4cCI6MjA2NzM2NjY2MH0.YJZzStrOdGG9lQRqFdQH6rq79K1tXBFWxCS_vglyGII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});